#sendgrid env variables:
export SENDGRID_USERNAME=apikey
export SENDGRID_PASSWORD=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
#Stripe env variables:
export STRIPE_TEST_PUBLISHABLE_KEY=pk_test_wvOyE1z0g2uox7TkKdPla6w0
export STRIPE_TEST_SECRET_KEY=sk_test_QO3KseslV3h1QBR4UUCZUK8O


# STRIPE_TEST_PUBLISHABLE_KEY=pk_test_wvOyE1z0g2uox7TkKdPla6w0 ; STRIPE_TEST_SECRET_KEY=sk_test_QO3KseslV3h1QBR4UUCZUK8O ./run