#sendgrid env variables:
export SENDGRID_USERNAME=apikey
export SENDGRID_PASSWORD=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
#Stripe env variables:
#export STRIPE_TEST_PUBLISHABLE_KEY=pk_test_wvOyE1z0g2uox7TkKdPla6w0
#export STRIPE_TEST_SECRET_KEY=sk_test_QO3KseslV3h1QBR4UUCZUK8O


